### ISSUE TITLE
crash during server startup

### ISSUE THREAD

**Issue by altano** [talrey/CreateDeco#107]
I'm trying to run an _All the Mods 7 - To The Sky_ modpack that includes Create Deco, which seems to be causing a failure during startup:

```
minecraft-atm7sky  | [01:12:49] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createdeco, class com.github.talrey.createdeco.CreateDecoMod
minecraft-atm7sky  | java.lang.reflect.InvocationTargetException: null
minecraft-atm7sky  |    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
minecraft-atm7sky  |    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.1.jar%23265!/:?] {}
minecraft-atm7sky  |    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.1.jar%23264!/:?] {}
minecraft-atm7sky  |    at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:computing_frames}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:computing_frames}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {}
minecraft-atm7sky  | Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/util/NonNullSupplier
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.initialize(SheetMetal.java:51) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.registerBlocks(SheetMetal.java:202) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.Registration.registerBlocks(Registration.java:395) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:52) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    ... 14 more
minecraft-atm7sky  | Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.util.NonNullSupplier
minecraft-atm7sky  |    at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.initialize(SheetMetal.java:51) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.registerBlocks(SheetMetal.java:202) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.Registration.registerBlocks(Registration.java:395) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:52) ~[createdeco-1.3.0-1.18.2.jar%2395!/:1.3.0-1.18.2] {re:classloading}
minecraft-atm7sky  |    ... 14 more
```

This is on Java 17.

I can provide more information but I'm not sure what's useful.

**Comment by altano** [comment]
Seems to reproduce in 1.3.3 as well:

```
minecraft-atm7sky  | [02:19:25] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createdeco, class com.github.talrey.createdeco.CreateDecoMod
minecraft-atm7sky  | java.lang.reflect.InvocationTargetException: null
minecraft-atm7sky  |    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
minecraft-atm7sky  |    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.1.jar%23266!/:?] {}
minecraft-atm7sky  |    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.1.jar%23265!/:?] {}
minecraft-atm7sky  |    at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:computing_frames}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:computing_frames}
minecraft-atm7sky  |    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {}
minecraft-atm7sky  | Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/core/StitchedSprite
minecraft-atm7sky  |    at com.simibubi.create.foundation.block.render.SpriteShiftEntry.set(SpriteShiftEntry.java:13) ~[create-1.18.2-0.5.0.i.jar%2393!/:0.5.0.i] {re:classloading}
minecraft-atm7sky  |    at com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(CTSpriteShifter.java:20) ~[create-1.18.2-0.5.0.i.jar%2393!/:0.5.0.i] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.connected.SpriteShifts.populateMaps(SpriteShifts.java:27) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.connected.SpriteShifts.<clinit>(SpriteShifts.java:19) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.buildSheetMetalBlock(SheetMetal.java:72) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.lambda$registerBlocks$31(SheetMetal.java:207) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.registerBlocks(SheetMetal.java:202) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.Registration.registerBlocks(Registration.java:391) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:52) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    ... 14 more
minecraft-atm7sky  | Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.core.StitchedSprite
minecraft-atm7sky  |    at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
minecraft-atm7sky  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
minecraft-atm7sky  |    at com.simibubi.create.foundation.block.render.SpriteShiftEntry.set(SpriteShiftEntry.java:13) ~[create-1.18.2-0.5.0.i.jar%2393!/:0.5.0.i] {re:classloading}
minecraft-atm7sky  |    at com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(CTSpriteShifter.java:20) ~[create-1.18.2-0.5.0.i.jar%2393!/:0.5.0.i] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.connected.SpriteShifts.populateMaps(SpriteShifts.java:27) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.connected.SpriteShifts.<clinit>(SpriteShifts.java:19) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.buildSheetMetalBlock(SheetMetal.java:72) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.lambda$registerBlocks$31(SheetMetal.java:207) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
minecraft-atm7sky  |    at com.github.talrey.createdeco.registry.SheetMetal.registerBlocks(SheetMetal.java:202) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.Registration.registerBlocks(Registration.java:391) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:52) ~[createdeco-1.3.3-1.18.2.jar%2396!/:1.3.3-1.18.2] {re:classloading}
minecraft-atm7sky  |    ... 14 more
minecraft-atm7sky  | [02:19:25] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source ftbchunks
```
