### ISSUE TITLE
server crash when adding CreateDeco

### ISSUE THREAD

**Issue by L0rne** [talrey/CreateDeco#12]
I tested the mod on a single-player world and it works fine, but if I add it to my server and restart I get a crash with the attached crash report.

This is using  createdeco-1.2.3-1.18 with the latest versions of Create and Forge

[crash-2022-01-29_17.16.41-fml.txt](https://github.com/talrey/CreateDeco/files/7964224/crash-2022-01-29_17.16.41-fml.txt)

**Comment by UdoMorgenstern** [comment]
had a similar issue today on or server using createdeco-1.2.4-1.18 
in my case the problem was that flywheel is not needed anymore on the server side, BUT create deco is referencing flywheel in their sources/build options

**Workaround**: I added flywheel mod to the server and it was starting

**Comment by L0rne** [comment]
Adding Flywheel to the server got things working for me, too.

**Comment by SplendidAlakey** [comment]
This is now also an issue in the fabric port. There're no public Flywheel builds available, I tried compiling one from source, but it didn't solve the issue.

**Comment by StockiesLad** [comment]
Same issue here!

**Comment by ghost** [comment]
edit: adding the current git build of flywheel does indeed not help for fabric.

Here's useful info aside from the "it doesn't work!" +1 posts:

```
[15:29:36] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createdeco'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.8-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/util/NonNullSupplier
at com.github.talrey.createdeco.registry.Props.registerItems(Props.java:253) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at com.github.talrey.createdeco.Registration.registerItems(Registration.java:535) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at com.github.talrey.createdeco.CreateDecoMod.onInitialize(CreateDecoMod.java:42) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
... 8 more
Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.util.NonNullSupplier
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at com.github.talrey.createdeco.registry.Props.registerItems(Props.java:253) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at com.github.talrey.createdeco.Registration.registerItems(Registration.java:535) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at com.github.talrey.createdeco.CreateDecoMod.onInitialize(CreateDecoMod.java:42) ~[createdeco-1.2.7a-fabric-1.18.2.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
... 8 more
```

Complete: https://mclo.gs/hDE2lQq

**Comment by StockiesLad** [comment]
go into flywheel in the create "metaING/jars" and change the fabric.mod of flywheel to run in both environments.

**Comment by Gamerbolts** [comment]
Hello. Having the same issue as above for Fabric. I am in the fabric.mod of flywheel and I see where it says client. What do I change this to?

{"schemaVersion":1,"id":"flywheel","version":"1.18-0.7.0.26","name":"Flywheel","description":"A modern engine for modded minecraft.","authors":["Jozufozu","Pepper_Bell"],"contact":{"homepage":"https://www.curseforge.com/minecraft/mc-mods/flywheel","issues":"https://github.com/Jozufozu/Flywheel/issues","sources":"https://github.com/Jozufozu/Flywheel"},"license":"MIT","icon":"logo.png","environment":"client","entrypoints":{"client":["com.jozufozu.flywheel.Flywheel"]},"mixins":["flywheel.mixins.json","flywheel.fabric.mixins.json","flywheel.sodium.mixins.json"],"depends":{"fabricloader":">=0.11.3","fabric":"*","minecraft":">=1.18.2","java":">=17"}}

**Comment by SplendidAlakey** [comment]
> Hello. Having the same issue as above for Fabric. I am in the fabric.mod of flywheel and I see where it says client. What do I change this to?

Change it to "*"

**Comment by ghost** [comment]
`"environment":"client"` --> `"environment":"*"` 

For clarity.

**Comment by Gamerbolts** [comment]
Thank you. I did that and it worked perfectly!
