### ISSUE TITLE
Complete server crash on shift-wrenching catwalk railings (Fabric)

### ISSUE THREAD

**Issue by cajecans** [talrey/CreateDeco#160]
As explained in the title, a fabric server I play on with this mod installed crashes whenever you shift-right click on a catwalk railing while holding a wrench. This happens with most, if not all, types of catwalk railings.

**Comment by cai-tan** [comment]
This is fixed in a recent update.

**Comment by lexi-the-cute** [comment]
> This is fixed in a recent update.

good to know. will check to see if all my mods are updated.

```
[05:25:35 ERROR] [Server thread]: [MinecraftServer] Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_638
        at com.github.talrey.createdeco.blocks.CatwalkRailingBlock.onSneakWrenched(CatwalkRailingBlock.java:77) ~[createdeco-2.0.1-1.20.1-fabric.jar:?]
        at com.simibubi.create.content.equipment.wrench.WrenchItem.useOn(WrenchItem.java:54) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:272) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:363) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1140) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:22) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:12818) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:115) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bed000$carpet$modifiedRunLoop(MinecraftServer.java:14451) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 22 more
[05:25:35 ERROR] [Server thread]: [MinecraftServer] This crash report has been saved to: /mnt/minecraft/fabric/./crash-reports/crash-2024-06-17_05.25.35-server.txt
```

**Comment by lexi-the-cute** [comment]
yep, the update fixed it. did find out that create doesnt like the newest version of iris though. still have to take a look at creating a minimal setup to cause the instant crash
