### ISSUE TITLE
Crash on dedicated server init stage (your mod might have a lot of client only methods incorrectly tagged)

### ISSUE THREAD

**Issue by NighthowlerStudios** [talrey/CreateDeco#5]
Mod File: createdeco-1.1.2-1.16.5.jar
        Failure message: Create Deco (createdeco) has failed to load correctly
                java.lang.NoSuchMethodError: com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(Lcom/simibubi/create/foundation/block/connected/CTSpriteShifter$CTType;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)Lcom/simibubi/create/foundation/block/connected/CTSpriteShiftEntry;
        Mod Version: 1.1.2-1.16.5
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.NoSuchMethodError: com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(Lcom/simibubi/create/foundation/block/connected/CTSpriteShifter$CTType;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)Lcom/simibubi/create/foundation/block/connected/CTSpriteShiftEntry;
Stacktrace:
        at com.github.talrey.createdeco.connected.SpriteShifts.populateMaps(SpriteShifts.java:26) ~[createdeco:1.1.2-1.16.5] {re:classloading}
        at com.github.talrey.createdeco.connected.SpriteShifts.<clinit>(SpriteShifts.java:18) ~[createdeco:1.1.2-1.16.5] {re:classloading}
        at com.github.talrey.createdeco.Registration.lambda$registerBlocks$113(Registration.java:821) ~[createdeco:1.1.2-1.16.5] {re:classloading}
        at java.util.HashMap.forEach(HashMap.java:1290) ~[?:1.8.0_312] {}
        at com.github.talrey.createdeco.Registration.registerBlocks(Registration.java:768) ~[createdeco:1.1.2-1.16.5] {re:classloading}
        at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:58) ~[createdeco:1.1.2-1.16.5] {re:classloading}

**Comment by NighthowlerStudios** [comment]
strange.  git decided to format that weirdly.  oh well, still has all the info
