### ISSUE TITLE
[1.16] Horrible Log Spam

### ISSUE THREAD

**Issue by TheMysticalBard** [talrey/CreateDeco#57]
Running latest version for 1.16, 1.1.2, and the logs are constantly being spammed while playing. This is the message that keeps repeating:
```[Worker-Main-13/WARN] [java.lang.String/]: Discovery error in createdeco:netherite_mesh_fence#east=false,north=false,north_east=false,north_west=true,south=false,south_east=true,south_west=true,waterlogged=false,west=false
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:builtin/missing#missing
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
	at mods.betterfoliage.config.match.MatchRules$anyModel$1.invoke(Rules.kt:150) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MatchRules$anyModel$1.invoke(Rules.kt:16) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MComparison.compare(Match.kt:146) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MatchRules.mModel(Rules.kt:100) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MatchRules.mMatchList(Rules.kt:41) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MatchRules.mNode(Rules.kt:28) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.config.match.MatchRules.visitRoot(Rules.kt:20) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.resource.discovery.RuleBasedDiscovery.processBlockModel(RuleBasedDiscovery.kt:59) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.resource.discovery.RuleBasedDiscovery.processModel(RuleBasedDiscovery.kt:43) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.resource.discovery.AbstractModelDiscovery.onModelsLoaded(ModelDiscovery.kt:26) ~[betterfoliage:2.7.1]
	at mods.betterfoliage.resource.discovery.BakeWrapperManager.handleModelLoad(BakingLifecycle.kt:94) ~[betterfoliage:2.7.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1865_BakeWrapperManager_handleModelLoad_ModelDefinitionsLoadedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at thedarkcolour.kotlinforforge.eventbus.KotlinEventBus$post$1.invoke(KotlinEventBus.kt:369) ~[?:?]
	at thedarkcolour.kotlinforforge.eventbus.KotlinEventBus$post$1.invoke(KotlinEventBus.kt:369) ~[?:?]
	at thedarkcolour.kotlinforforge.eventbus.KotlinEventBus.post(KotlinEventBus.kt:382) ~[?:?]
	at thedarkcolour.kotlinforforge.eventbus.KotlinEventBus.post(KotlinEventBus.kt:369) ~[?:?]
	at net.minecraft.client.renderer.model.ModelBakery.handler$cbb000$onBeforeTextures(ModelBakery.java:2647) ~[?:?]
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:195) ~[?:?]
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[forge:?]
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?]
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by talrey** [comment]
Looks like an issue with Better Foliage. Have you reported this to them?
