### ISSUE TITLE
Placing a Black Decal on the top of a block crashes the server

### ISSUE THREAD

**Issue by pureFakeItalian** [talrey/CreateDeco#70]
When you attempt to place a decal on the top side of a block, the server hangs, and crashes with this error.
This might extend to the other decals and to the 'up' orientation as well, but I haven't tested that extensively.
BTW, I'm not implying that the decals should have more orientations, but trying to place them incorrectly shouldn't crash the server.

[crash-2023-04-26_20.58.42-client.txt](https://github.com/talrey/CreateDeco/files/11338595/crash-2023-04-26_20.58.42-client.txt)

--Transcription of Error--

Time: 4/26/23, 8:58 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to down on Block{createdeco:black_decal}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.github.talrey.createdeco.blocks.DecalBlock.m_5573_(DecalBlock.java:66) ~[createdeco-1.3.1-1.18.2.jar%23124!/:1.3.1-1.18.2] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_5965_(BlockItem.java:117) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,re:classloading,pl:mixin:APP:miniextras.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:63) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,re:classloading,pl:mixin:APP:miniextras.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,re:classloading,pl:mixin:APP:miniextras.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:223) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:showcaseitem.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:238) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:showcaseitem.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:223) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:showcaseitem.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:309) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1573) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.redirect$dfc000$onDoItemUse(Minecraft.java:12401) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1855) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1670) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23333!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] {}

**Comment by pureFakeItalian** [comment]
I double-checked with a clean instance; it's not a mod incompability BTW.

**Comment by MsKarMagick** [comment]
This extends to other color decals as well.

`The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to down on Block{createdeco:red_decal}, it is not an allowed value`

**Comment by talrey** [comment]
Apologies. This'll be a simple fix, I'll get it out when I can.
